apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ueransim05
  namespace: open5gs
  labels:
    epc-mode: ueransim05
    app: ueransim
spec:
  replicas: 0
  selector:
    matchLabels:
      epc-mode: ueransim05
  template:
    metadata:    
      labels:
        epc-mode: ueransim05
        app: ueransim
    spec:  
      nodeSelector:
        #nodetype: server
        #kubernetes.io/arch: amd64
        #kubernetes.io/hostname: erasure
        #kubernetes.io/hostname: petshopboys
        kubernetes.io/hostname: brix-porvir-03
      initContainers:
        - name: init-gnb
          image: maikovisky/ueransim:3.2.6
          imagePullPolicy: Always
          command: ["/bin/gnbinit"]
          volumeMounts:
            - name: open5gs-ueransim-gnbinit
              mountPath: /bin/gnbinit
              subPath: "gnbinit"

            - name: open5gs-ueransim-gnb-config
              mountPath: /etc/ueransim/open5gs-gnb-base.yaml
              subPath: "open5gs-gnb-base.yaml"

            - name: etc-tmp
              mountPath: /etc/ueransim/tmp

      containers:       
        - name: ueransim-gnb
          image: maikovisky/ueransim:3.2.6  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
                      
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

            - name: open5gs-ueransim-gnb-config
              mountPath: /etc/ueransim/open5gs-gnb-base.yaml
              subPath: "open5gs-gnb-base.yaml"

            - name: etc-tmp
              mountPath: /etc/ueransim/tmp

          command: ["nr-gnb", "-c", "/etc/ueransim/tmp/open5gs-gnb-01.yaml"]

      volumes:
        - name: open5gs-ueransim-gnb-config
          configMap:
            name: open5gs-ueransim-gnb-config

        - name: open5gs-ueransim-gnbinit
          configMap:
            name: open5gs-ueransim-gnbinit
            defaultMode: 0777

        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun


        - name: etc-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-ueransim05
  namespace: open5gs
  labels:
    epc-mode: ueransim05
spec:
  selector:
    epc-mode: ueransim05
  ports:
    - name: http2-open5gs-ueransim05-80
      protocol: TCP
      port: 80
    - name: open5gs-ueransim05-tcp-3000
      protocol: TCP
      port: 3000
    # - name: http2-open5gs-ueransim05-9100
    #   protocol: TCP
    #   port: 9100
    - name: open5gs-ueransim05-udp-2152
      protocol: UDP
      port: 2152
    - name: open5gs-ueransim05-udp-36743
      protocol: UDP
      port: 36743
    - name: open5gs-ueransim05-udp-4997
      protocol: UDP
      port: 4997
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: open5gs-ueransim05
#   namespace: open5gs
#   labels:
#     epc-mode: ueransim05
# spec:
#   selector:
#     matchLabels:
#       epc-mode: ueransim05
#   endpoints:
#   - interval: 5s
#     port: open5gs-ueransim05-tcp-9100