apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ueransim01
  namespace: open5gs
  labels:
    epc-mode: ueransim01
    app: ueransim
spec:
  replicas: 0
  selector:
    matchLabels:
      epc-mode: ueransim01
  template:
    metadata:    
      labels:
        epc-mode: ueransim01
        app: ueransim
    spec:  
      nodeSelector:
        kubernetes.io/hostname: brix-porvir-02
      initContainers:
        - name: init-gnb
          image: maikovisky/ueransim:3.2.6
          imagePullPolicy: IfNotPresent
          command: ["/bin/gnbinit"]
          volumeMounts:
            - name: open5gs-ueransim-gnbinit
              mountPath: /bin/gnbinit
              subPath: "gnbinit"

            - name: open5gs-ueransim-gnb-config
              mountPath: /etc/ueransim/open5gs-gnb-base.yaml
              subPath: "open5gs-gnb-base.yaml"

            - name: etc-tmp
              mountPath: /etc/ueransim/tmp

      containers:
        - name: ueransim-gnb
          image: maikovisky/ueransim:3.2.6  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          resources:
            requests:
              memory: "0"
              cpu: "1500m"
            limits:
              memory: "0"
              cpu: "1500m"
                      
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

            - name: open5gs-ueransim-gnb-config
              mountPath: /etc/ueransim/open5gs-gnb-base.yaml
              subPath: "open5gs-gnb-base.yaml"

            - name: etc-tmp
              mountPath: /etc/ueransim/tmp

          command: ["nr-gnb", "-c", "/etc/ueransim/tmp/open5gs-gnb-01.yaml"]
      volumes:
        - name: open5gs-ueransim-gnb-config
          configMap:
            name: open5gs-ueransim-gnb-config

        - name: open5gs-ueransim-gnbinit
          configMap:
            name: open5gs-ueransim-gnbinit
            defaultMode: 0777

        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

        - name: etc-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-ueransim01
  namespace: open5gs
  labels:
    epc-mode: ueransim01
spec:
  selector:
    epc-mode: ueransim01
  ports:
    - name: http2-open5gs-ueransim01-80
      protocol: TCP
      port: 80
    - name: open5gs-ueransim01-tcp-3000
      protocol: TCP
      port: 3000
    - name: open5gs-ueransim01-udp-2152
      protocol: UDP
      port: 2152
    - name: open5gs-ueransim01-udp-36743
      protocol: UDP
      port: 36743
    - name: open5gs-ueransim01-udp-4997
      protocol: UDP
      port: 4997
