apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ue-reconfig-iperf
  namespace: open5gs
  labels:
    epc-mode: ueransim
  defaultMode: 0777
data:
  reconfig-iperf: |
    #!/bin/bash 
    set -e

    echo "Sleep 180s"
    sleep 30s
    echo "Sleep 150s"
    sleep 30s
    echo "Sleep 120s"
    sleep 30s
    echo "Sleep 90s"
    sleep 30s
    echo "Sleep 60s"
    sleep 30s
    echo "Sleep 30s"
    sleep 30s

    # uesimtun0=$(ifconfig uesimtun0 | awk '/inet / {print $6}')
    uesimtun1=$(ifconfig uesimtun1 | awk '/inet / {print $6}')
    # if (expr "$uesimtun0" : "10\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$"")
    # then
    #   uesimtun=$uesimtun0
    # else
    #   uesimtun=$uesimtun1
    # fi
    echo "iperf -B $uesimtun1 -c open5gs-iperf -t 1800"
    iperf -B $uesimtun1 -c open5gs-iperf  -t 1800
    

  