apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ue-video-hd
  namespace: open5gs
  labels:
    epc-mode: ueransim
  defaultMode: 0777
data:
  testing: |
    #!/bin/bash 
    set -e

    sleep "15s"

    COUNTER=0
    while [ -z  $(ifconfig | awk  '/uesimtun/{print $1; exit}') ] 
    do
      let COUNTER=COUNTER+1
      #echo -ne "Waiting create tunnel interface. Attempt $COUNTER"\\r
      echo "Waiting create tunnel interface. Attempt $COUNTER"
      sleep "5s"
    done

    uesimtun0=$(ifconfig uesimtun0 | awk '/inet / {print $6}')
    uesimtun1=$(ifconfig uesimtun1 | awk '/inet / {print $6}')
    if [ $(expr "$uesimtun0" : "10\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$") ]
    then
      echo "Using interface uesimtun0 with IP $uesimtun0"
      uesimtun=$uesimtun0
    else
      echo "Using interface uesimtun1 with IP $uesimtun1"
      uesimtun=$uesimtun1
    fi

    route add -host open5gs-iperf0$SLICE dev uesimtun0
    while :
    do
      t=1800
      /bin/iperf -c open5gs-iperf0$SLICE -u -p 5002 --len 1370 -f A -i 15 -t $t --isochronous=60:6m,1m --trip-times -e -z
    done
