apiVersion: v1
kind: Service
metadata:
  name: open5gs-ue04
  namespace: open5gs
  labels:
    epc-mode: ue04
spec:
  selector:
    epc-mode: ue04
  ports:
    - name: http2-open5gs-ue04-80
      protocol: TCP
      port: 80
    - name: open5gs-ue04-tcp-3000
      protocol: TCP
      port: 3000
    - name: http2-open5gs-ue04-9100
      protocol: TCP
      port: 9100
    - name: open5gs-ue04-udp-2152
      protocol: UDP
      port: 2152
    - name: open5gs-ue04-udp-36743
      protocol: UDP
      port: 36743
    - name: open5gs-ue04-udp-4997
      protocol: UDP
      port: 4997
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ue04
  namespace: open5gs
  labels:
    epc-mode: ue04
spec:
  replicas: 0
  selector:
    matchLabels:
      epc-mode: ue04
  template:
    metadata:    
      labels:
        epc-mode: ue04
        app: ueransim-ue04
    spec:  
      nodeSelector:
        #nodetype: server
        #kubernetes.io/arch: amd64
        #kubernetes.io/hostname: molejo
        # kubernetes.io/hostname: mac-porvir-05
        kubernetes.io/hostname: brix-porvir-05
      initContainers:
        - name: init-ue
          image: maikovisky/ueransim:3.2.6
          imagePullPolicy: Always
          command: ["/bin/ueinit"]
          env:            
            - name: DATABASE_URL
              value: mongodb://open5gs-mongodb-svc:27017
            - name: IMSI
              value: "999700000000000"
            - name: RANDOM_SLICE
              value: "False"
            - name: SLICE
              value: "4"

          volumeMounts:
            - name: open5gs-ue-init
              mountPath: /bin/ueinit
              subPath: "ueinit"

            - name: open5gs-ue-init
              mountPath: "/bin/initUE.py"
              subPath: "initUE.py"

            - name: etc-ue-tmp
              mountPath: /etc/ueransim/tmp
      containers:      
        # - name: tcpdump-ue
        #   image: maikovisky/open5gs:ubuntu-latest    
        #   command: ["/bin/tcpdump", "-i", "eth0", "-s", "65535", "-G", "3600", "-w", "/var/tcpdump/ue-%F_%H%M.pcap"]
        #   volumeMounts:
        #     - name: "dev-net-tun"
        #       mountPath: "/dev/net/tun" # Needed for VPN
        #     - name: tcpdump-persistent-storage
        #       mountPath: /var/tcpdump


        - name: main-ue
          image: maikovisky/ueransim:3.2.6  
          imagePullPolicy: "Always" 
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "nr-cli --dump | xargs -i nr-cli {} -e 'deregister remove-sim'"]
          env:            
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MCC
              value: "999"
            - name: MNC
              value: "70"
              
          volumeMounts:         
            - name: open5gs-ue-init
              mountPath: "/bin/initUE.py"
              subPath: "initUE.py"

            - name: etc-ue-tmp
              mountPath: /etc/ueransim/tmp

            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

          command: ["nr-ue", "-c", "/etc/ueransim/tmp/open5gs-ue-01.yaml"]

        # - name: metrics-ue
        #   image: maikovisky/ueransim:3.2.6     
        #   imagePullPolicy: "Always"
        #   command: ["/bin/prometheus-node-exporter", "--collector.disable-defaults", "--collector.textfile", "--collector.arp","--collector.netclass" ,"--collector.netdev" ,"--collector.netstat" ,"--collector.udp_queues","--collector.ipvs","--collector.cpu","--collector.cpufreq","--collector.meminfo"]
        #   volumeMounts:
        #     - name: "dev-net-tun"
        #       mountPath: "/dev/net/tun" # Needed for VPN
        - name: iperf-ue
          image: maikovisky/ueransim:3.2.6  
          imagePullPolicy: "Always" 
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          env:  
            - name: SLICE
              value: "4"
          command: ["/bin/testing"]
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

            - name: open5gs-ue-testing
              mountPath: /bin/testing
              subPath: "testing"

        - name: "telegraf"
          image: "telegraf:latest"
          volumeMounts:
            - name: open5gs-ue4-telegraf-config
              mountPath: /etc/telegraf
          
      volumes:
        - name: open5gs-ue4-telegraf-config
          configMap:
            name: open5gs-ue4-telegraf-config
        - name: open5gs-ue-testing
          configMap:
            name: open5gs-ue-testing
            defaultMode: 0777

        - name: open5gs-ue-init
          configMap:
            name: open5gs-ue-init
            defaultMode: 0777

        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

        - name: etc-ue-tmp
          emptyDir: {}

        - name: tcpdump-persistent-storage
          persistentVolumeClaim:
            claimName: open5gs-tcpdump-pv-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ue4-telegraf-config
  namespace: open5gs
data:
  telegraf.conf: |+
    [[outputs.prometheus_client]]
      ## Address to listen on.
      listen = ":9100"


    [[inputs.ping]]
      urls = ["10.245.25.134", "8.8.8.8"]
      interface = "uesimtun0"


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-ue04
  namespace: open5gs
  labels:
    epc-mode: ue04
spec:
  selector:
    matchLabels:
      epc-mode: ue04
  endpoints:
  - interval: 10s
    port: http2-open5gs-ue04-9100
