apiVersion: v1
kind: Service
metadata:
  name: open5gs-ue09
  namespace: open5gs
  labels:
    epc-mode: ue09
spec:
  selector:
    epc-mode: ue09
  ports:
    - name: http2-open5gs-ue09-80
      protocol: TCP
      port: 80
    - name: open5gs-ue09-tcp-3000
      protocol: TCP
      port: 3000
    - name: http2-open5gs-ue09-9100
      protocol: TCP
      port: 9100
    - name: open5gs-ue09-udp-2152
      protocol: UDP
      port: 2152
    - name: open5gs-ue09-udp-36743
      protocol: UDP
      port: 36743
    - name: open5gs-ue09-udp-4997
      protocol: UDP
      port: 4997
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ue09
  namespace: open5gs
  labels:
    epc-mode: ue09
spec:
  replicas: 0
  selector:
    matchLabels:
      epc-mode: ue09
  template:
    metadata:    
      labels:
        epc-mode: ue09
        app: ueransim-ue09
    spec:  
      nodeSelector:
        #nodetype: server
        #kubernetes.io/arch: amd64
        #kubernetes.io/hostname: molejo
        kubernetes.io/hostname: mac-porvir-02
      initContainers:
        - name: init-ue
          image: maikovisky/ueransim:3.2.6
          imagePullPolicy: IfNotPresent
          command: ["/bin/ueinit"]
          env:            
            - name: DATABASE_URL
              value: mongodb://open5gs-mongodb-svc:27017
            - name: IMSI
              value: "999700000000000"
            - name: RANDOM_SLICE
              value: "False"
            - name: SLICE
              value: "9"

          volumeMounts:
            - name: open5gs-ue-init
              mountPath: /bin/ueinit
              subPath: "ueinit"

            - name: open5gs-ue-init
              mountPath: "/bin/initUE.py"
              subPath: "initUE.py"

            - name: etc-ue-tmp
              mountPath: /etc/ueransim/tmp
      containers:      
        # - name: tcpdump-ue
        #   image: maikovisky/open5gs:ubuntu-latest    
        #   command: ["/bin/tcpdump", "-i", "eth0", "-s", "65535", "-G", "3600", "-w", "/var/tcpdump/ue-%F_%H%M.pcap"]
        #   volumeMounts:
        #     - name: "dev-net-tun"
        #       mountPath: "/dev/net/tun" # Needed for VPN
        #     - name: tcpdump-persistent-storage
        #       mountPath: /var/tcpdump


        - name: main-ue
          image: maikovisky/ueransim:3.2.6  
          imagePullPolicy: "IfNotPresent" 
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          env:            
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MCC
              value: "999"
            - name: MNC
              value: "70"
              
          volumeMounts:         
            - name: open5gs-ue-init
              mountPath: "/bin/initUE.py"
              subPath: "initUE.py"

            - name: etc-ue-tmp
              mountPath: /etc/ueransim/tmp

            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

          command: ["nr-ue", "-c", "/etc/ueransim/tmp/open5gs-ue-01.yaml"]

        # - name: metrics-ue
        #   image: maikovisky/ueransim:3.2.6     
        #   imagePullPolicy: "IfNotPresent"
        #   command: ["/bin/prometheus-node-exporter", "--collector.disable-defaults", "--collector.textfile", "--collector.arp","--collector.netclass" ,"--collector.netdev" ,"--collector.netstat" ,"--collector.udp_queues","--collector.ipvs","--collector.cpu","--collector.cpufreq","--collector.meminfo"]
        #   volumeMounts:
        #     - name: "dev-net-tun"
        #       mountPath: "/dev/net/tun" # Needed for VPN
        - name: iperf-ue
          image: maikovisky/ueransim:3.2.6  
          imagePullPolicy: "IfNotPresent" 
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          env:  
            - name: SLICE
              value: "9"
          command: ["/bin/testing"]
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

            - name: open5gs-ue-testing
              mountPath: /bin/testing
              subPath: "testing"
          
      volumes:
        - name: open5gs-ue-testing
          configMap:
            name: open5gs-ue-testing
            defaultMode: 0777

        - name: open5gs-ue-init
          configMap:
            name: open5gs-ue-init
            defaultMode: 0777

        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

        - name: etc-ue-tmp
          emptyDir: {}

        - name: tcpdump-persistent-storage
          persistentVolumeClaim:
            claimName: open5gs-tcpdump-pv-claim


      

