apiVersion: v1
kind: Service
metadata:
  name: open5gs-ueransim
  namespace: open5gs
  labels:
    epc-mode: ueransim
spec:
  selector:
    epc-mode: ueransim
  ports:
    - name: open5gs-ueransim-tcp-80
      protocol: TCP
      port: 80
    - name: open5gs-ueransim-tcp-3000
      protocol: TCP
      port: 3000
    - name: open5gs-ueransim-tcp-9100
      protocol: TCP
      port: 9100
    - name: open5gs-ueransim-udp-2152
      protocol: UDP
      port: 2152
    - name: open5gs-ueransim-udp-36743
      protocol: UDP
      port: 36743
    - name: open5gs-ueransim-udp-4997
      protocol: UDP
      port: 4997
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open5gs-ingress-ueransim-2152
  namespace: open5gs
spec:
  defaultBackend:
    service:
      name: open5gs-ueransim-udp-2152
      port:
        number: 2152
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open5gs-ingress-ueransim-36743
  namespace: open5gs
spec:
  defaultBackend:
    service:
      name: open5gs-ueransim-udp-36743
      port:
        number: 36743
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open5gs-ingress-ueransim-4997
  namespace: open5gs
spec:
  defaultBackend:
    service:
      name: open5gs-ueransim-udp-4997
      port:
        number: 4997
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ueransim
  namespace: open5gs
  labels:
    epc-mode: ueransim
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: ueransim
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: ueransim
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: metrics-ueransim
          image: maikovisky/open5gs:latest  
          command: ["/usr/bin/node_exporter"]
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN


        - name: ueransim
          image: maikovisky/ueransim:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: linkIp
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ngapIp
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: gtpIp
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: open5gs-ueransim-reconfig
              mountPath: /bin/reconfig
              subPath: "reconfig"
            - name: open5gs-ueransim-gnb-config
              mountPath: /etc/ueransim/open5gs-gnb-base.yaml
              subPath: "open5gs-gnb-base.yaml"
            - name: open5gs-ueransim-ue-config
              mountPath: /etc/ueransim/open5gs-ue-base.yaml
              subPath: "open5gs-ue-base.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          command: ["/bin/reconfig"]
          #command: ["sleep", "1d"]
          #command: ["nr-gnb", "-c", "/etc/ueransim/open5g-gnb.yaml"]
      volumes:
        - name: open5gs-ueransim-reconfig
          configMap:
            name: open5gs-ueransim-reconfig
            defaultMode: 0777
        - name: open5gs-ueransim-gnb-config
          configMap:
            name: open5gs-ueransim-gnb-config
        - name: open5gs-ueransim-ue-config
          configMap:
            name: open5gs-ueransim-ue-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-ueransim
  namespace: open5gs
  labels:
    epc-mode: ueransim
spec:
  selector:
    matchLabels:
      epc-mode: ueransim
  endpoints:
  - interval: 30s
    port: open5gs-ueransim-tcp-9100