apiVersion: v1
kind: Service
metadata:
  name: open5gs-ueransim
  namespace: open5gs
  labels:
    epc-mode: ueransim
spec:
  selector:
    epc-mode: ueransim
  ports:
    - name: open5gs-ueransim-tcp-80
      protocol: TCP
      port: 80
    - name: open5gs-ueransim-tcp-3000
      protocol: TCP
      port: 3000
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ueransim
  namespace: open5gs
  labels:
    epc-mode: ueransim
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: ueransim
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: ueransim
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: ueransim
          image: maikovisky/ueransim:1.1  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: open5gs-ueransim-reconfig
              mountPath: /bin/reconfig
              subPath: "reconfig"
            - name: open5gs-ueransim-gnb-config
              mountPath: /etc/ueransim/open5gs-gnb-base.yaml
              subPath: "open5gs-gnb-base.yaml"
            - name: open5gs-ueransim-ue-config
              mountPath: /etc/ueransim/open5gs-ue-base.yaml
              subPath: "open5gs-ue-base.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          #command: ["sed", "-i", ""]
          #command: ["top"]
          command: ["/bin/reconfig"]
          #command: ["/bin/reconfig", "&&", "nr-gnb", "-c", "/etc/uesinran/open5g-gnb-01.yaml"]
      volumes:
        - name: open5gs-ueransim-reconfig
          configMap:
            name: open5gs-ueransim-reconfig
            defaultMode: 0777
        - name: open5gs-ueransim-gnb-config
          configMap:
            name: open5gs-ueransim-gnb-config
        - name: open5gs-ueransim-ue-config
          configMap:
            name: open5gs-ueransim-ue-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

