apiVersion: v1
kind: Service
metadata:
  name: open5gs-mongodb-svc
  namespace: open5gs
spec:
  ports:
  - port: 27017
    name: mongo-open5gs-27017
  selector:
    app: open5gs-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mongodb
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-mongodb
      
  template:
    metadata:
      labels:
        app: open5gs-mongodb
        version: v4.4
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        #kubernetes.io/hostname: molejo
        nodetype: server

      containers:
      - image: free5gmano/nextepc-mongodb
        name: open5gs-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        #command: ["sleep", "1d"]
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: open5gs-mongodb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open5gs-mongodb-pv-claim
  namespace: open5gs
spec:
  storageClassName: rook-ceph-fs-simple
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
