apiVersion: v1
kind: Service
metadata:
  name: open5gs-nssf
  namespace: open5gs
  labels:
    epc-mode: nssf
spec:
  selector:
    epc-mode: nssf
  ports:
    - name: open5gs-nssf-tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: open5gs-nssf-tcp-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-nssf
  namespace: open5gs
  labels:
    epc-mode: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nssf
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: nssf
    spec:  
      containers:
        - name: metrics-nssf
          image: maikovisky/open5gs:latest  
          command: ["/usr/bin/node_exporter"]

        - name: nssf
          image: maikovisky/open5gs:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: open5gs-nssf-config
              mountPath: /open5gs/config-map/nssf.yaml
              subPath: "nssf.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          command: ["open5gs-nssfd", "-c", "/open5gs/config-map/nssf.yaml"]
      volumes:
        - name: open5gs-nssf-config
          configMap:
            name: open5gs-nssf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-nssf
  namespace: open5gs
  labels:
    epc-mode: nssf
spec:
  selector:
    matchLabels:
      epc-mode: nssf
  endpoints:
  - interval: 30s
    port: open5gs-nssf-tcp-9100
