apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |
    logger:
        file: /var/log/open5gs/nssf.log

    nssf:
        sbi:
          - addr: 0.0.0.0
            advertise: open5gs-nssf
        nsi:
          - addr: 0.0.0.0
            s_nssai:
              sst: 1
    nrf:
        sbi:
          name: open5gs-nrf