apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |
    logger:
      file: 
        path: /var/log/open5gs/nssf.log

    global:
      max:
        ue: 2048  # The number of UE can be increased depending on memory size.
        peer: 128

    nssf:
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-nssf
        client:
          nrf:
            - uri: http://open5gs-nrf

          nsi:
            - uri: http://open5gs-nrf
              s_nssai:
                sst: 1
            - uri: http://open5gs-nrf
              s_nssai:
                sst: 1
                sd: 000001
            - uri: http://open5gs-nrf
              s_nssai:
                sst: 2
                sd: 000002
            - uri: http://open5gs-nrf
              s_nssai:
                sst: 3
                sd: 000003
            - uri: http://open5gs-nrf
              s_nssai:
                sst: 4
                sd: 000004
            - uri: http://open5gs-nrf
              s_nssai:
                sst: 5
                sd: 000005
            - uri: http://open5gs-nrf
              s_nssai:
                sst: 6
                sd: 000006
            - uri: http://open5gs-nrf
              s_nssai:
                sst: 7
                sd: 000007
          #  - uri: http://open5gs-nrf
          #     s_nssai:
          #       sst: 8
          #       sd: 000008
            # - uri: http://open5gs-nrf
            #   s_nssai:
            #     sst: 9
            #     sd: 9
            # - uri: http://open5gs-nrf
            #   s_nssai:
            #     sst: 10
            #     sd: 10
            # - uri: http://open5gs-nrf
            #   s_nssai:
            #     sst: 11
            #     sd: 11
            # - uri: http://open5gs-nrf
            #   s_nssai:
            #     sst: 12
            #     sd: 12

              