apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |
    logger:
        file: /var/log/open5gs/nssf.log
    
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    nssf:
        sbi:
          - addr: 0.0.0.0
            advertise: open5gs-nssf
        nsi:
          - name: open5gs-nrf
            s_nssai:
              sst: 1
          - name: open5gs-nrf
            s_nssai:
              sst: 1
              sd: 1
          - name: open5gs-nrf
            s_nssai:
              sst: 2
              sd: 2
          - name: open5gs-nrf
            s_nssai:
              sst: 3
              sd: 3
          - name: open5gs-nrf
            s_nssai:
              sst: 4
              sd: 4

              
    # nrf:
    #     sbi:
    #       - name: open5gs-nrf
    
    scp:
        sbi:
          - name: open5gs-scp