apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-hss-config
  namespace: open5gs
  labels:
    epc-mode: hss
data:
  hss.yaml: |
    db_uri: mongodb://open5gs-mongodb-svc/open5gs
    logger:

        logger:
            file: /var/log/open5gs/hss.log

        hss:
          freeDiameter: /etc/freeDiameter/hss.conf
