apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: open5gs
  labels:
    epc-mode: amf
    app.kubernetes.io/name: open5gs
    app.kubernetes.io/component: amf
data:
  amf.yaml: |
    logger:
        # level: debug
        file: 
            path: /var/log/open5gs/amf.log

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
        peer: 64

    amf:
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-amf
        client:
          nrf:
            - uri: http://open5gs-nrf:80

      ngap: 
        server:
          - address: 0.0.0.0
            port: 38412

      guami:
        - plmn_id:
            mcc: 999
            mnc: 70
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 999
            mnc: 70
          tac: 1

      plmn_support:
        - plmn_id:
            mcc: 999
            mnc: 70
          s_nssai:
            - sst: 1
            - sst: 1
              sd: 000001
            - sst: 2
              sd: 000002
            - sst: 3
              sd: 000003
            - sst: 4
              sd: 000004
            - sst: 5
              sd: 000005
            # - sst: 6
            #   sd: 000006
        # - plmn_id:
        #     mcc: 999
        #     mnc: 70
        #   s_nssai:
        #     - sst: 5
        #       sd: 000005
        #     - sst: 6
        #       sd: 000006
        #     - sst: 7
        #       sd: 000007
        #     - sst: 8
        #       sd: 000008

        # - plmn_id:
        #     mcc: 999
        #     mnc: 70
        #   s_nssai:
        #     - sst: 9
        #       sd: 000009
        #     - sst: 10
        #       sd: 000010
        #     - sst: 11
        #       sd: 000011
        #     - sst: 12
        #       sd: 000012

      security:
          integrity_order : [ NIA2, NIA1, NIA0 ]
          ciphering_order : [ NEA0, NEA1, NEA2 ]
      network_name:
          full: Open5GS
      amf_name: open5gs-amf

      metrics:
        server:
          - address: 0.0.0.0
            port: 9090

      time:
        t3512:
          value: 540     # 9 mintues * 60 = 540 seconds
