apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: open5gs
  labels:
    epc-mode: amf
    app.kubernetes.io/name: open5gs
    app.kubernetes.io/component: amf
data:
  amf.yaml: |
    logger:
        file: /var/log/open5gs/amf.log
    amf:
        sbi:
          - addr: 0.0.0.0
            advertise: open5gs-amf

        ngap: 
          - dev: eth0

        guami:
          - plmn_id:
              mcc: 999
              mnc: 70
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: 999
              mnc: 70
            tac: 1
        plmn_support:
          - plmn_id:
              mcc: 999
              mnc: 70
            s_nssai:
              - sst: 1
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: open5gs
        amf_name: open5gs-amf

        metrics:
          addr: 0.0.0.0
          port: 9090

    nrf:
      sbi:
        name: open5gs-nrf
        
    usrsctp:

