apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-amf2
  namespace: open5gs
  labels:
    epc-mode: amf2
    promotheus: open5gs-monitor
    version:  2.7.1
    app.kubernetes.io/version: 2.7.1-27-g4f7f4ec
    app.kubernetes.io/part-of: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf2
  template:
    metadata:
      #annotations:
      # readiness.status.sidecar.istio.io/applicationPorts: "80"
      labels:
        epc-mode: amf2
        app: open5gs-amf2
        version:  2.7.1
    spec:  
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - open5gs-nrf
                topologyKey: kubernetes.io/hostname 
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
        #kubernetes.io/hostname: molejo

      containers:             
        - name: amf2
          image: maikovisky/open5gs:latest  
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - name: sctp-amf2
              containerPort: 38412
              protocol: SCTP
            - containerPort: 9090
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "750Mi"
              cpu: "500m"

          volumeMounts:
            - name: open5gs-amf2-config
              mountPath: /open5gs/config-map/amf.yaml
              subPath: "amf.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
            # - name: tcpdump-persistent-storage
            #   mountPath: /var/tcpdump

          command: ["open5gs-amfd",  "-c", "/open5gs/config-map/amf.yaml"]
          #command: ["sleep", "1d"]
      volumes:
        - name: open5gs-amf2-config
          configMap:
            name: open5gs-amf2-config

        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-amf2
  namespace: open5gs
  labels:
    epc-mode: amf2
spec:
  selector:
    matchLabels:
      epc-mode: amf2
  endpoints:
  - interval: 10s
    port: http-open5gs-amf2-9090
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf2
  namespace: open5gs
  labels:
    epc-mode: amf2
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: amf2
  ports:
    - name: http2-open5gs-amf2-80
      protocol: TCP
      port: 80 
      targetPort: 80
    - name: http-open5gs-amf2-9090
      protocol: TCP
      port: 9090 
    # - name: sctp-open5gs-amf2-38412
    #   protocol: SCTP
    #   targetPort: 38412
    #   port: 38412
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf2-sctp
  namespace: open5gs
  labels:
    epc-mode: amf2
    prometheus: open5gs-monitor
spec:
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  type: NodePort
  selector:
    epc-mode: amf2
  ports:
    - name: sctp-amf2
      protocol: SCTP
      port: 38412
      #targetPort: 30412
      nodePort: 30413
 