apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: open5gs
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    logger:
        file: /var/log/open5gs/udm.log
    
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    udm:
      hnet:
        - id: 1
          scheme: 1
          key: /etc/open5gs/hnet/curve25519-1.key
        - id: 2
          scheme: 2
          key: /etc/open5gs/hnet/secp256r1-2.key
        - id: 3
          scheme: 1
          key: /etc/open5gs/hnet/curve25519-3.key
        - id: 4
          scheme: 2
          key: /etc/open5gs/hnet/secp256r1-4.key
        - id: 5
          scheme: 1
          key: /etc/open5gs/hnet/curve25519-5.key
        - id: 6
          scheme: 2
          key: /etc/open5gs/hnet/secp256r1-6.key
      sbi:
        - dev: eth0
          advertise: open5gs-udm

    nrf:
      sbi:
        - name: open5gs-nrf
          
    # scp:
    #   sbi:
    #     - name: open5gs-scp


  

