apiVersion: v1
kind: Service
metadata:
  name: open5gs-udm
  namespace: open5gs
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
    - name: open5gs-udm-tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: open5gs-udm-tcp-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-udm
  namespace: open5gs
  labels:
    epc-mode: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:  
      labels:
        epc-mode: udm
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: metrics-udm
          image: maikovisky/open5gs:latest  
          command: ["/usr/bin/node_exporter"]

        - name: udm
          image: maikovisky/open5gs:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-udm-config
              mountPath: /open5gs/config-map/udm.yaml
              subPath: "udm.yaml"

          command: ["open5gs-udmd",  "-c", "/open5gs/config-map/udm.yaml"]
      volumes:
        - name: open5gs-udm-config
          configMap:
            name: open5gs-udm-config


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-udm
  namespace: open5gs
  labels:
    epc-mode: udm
spec:
  selector:
    matchLabels:
      epc-mode: udm
  endpoints:
  - interval: 30s
    port: open5gs-udm-tcp-9100