apiVersion: v1
kind: Service
metadata:
  name: open5gs-udm
  namespace: open5gs
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-udm
  namespace: open5gs
  labels:
    epc-mode: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: udm
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: udm
          image: maikovisky/open5gs:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: open5gs-udm-config
              mountPath: /open5gs/config-map/udm.yaml
              subPath: "udm.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          command: ["open5gs-udmd",  "-t", "-d", "-c", "/open5gs/config-map/udm.yaml"]
      volumes:
        - name: open5gs-udm-config
          configMap:
            name: open5gs-udm-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

