apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcf
  namespace: open5gs
  labels:
    epc-mode: pcf
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: pcf
  ports:
    - name: http2-open5gs-pcf-80
      protocol: TCP
      port: 80
    - name: http-open5gs-pcf-9090
      protocol: TCP
      port: 9090
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-pcf
  namespace: open5gs
  labels:
    epc-mode: pcf

spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: pcf
  template:
    metadata:  
      labels:
        epc-mode: pcf
        app: open5gs-pcf
        prometheus: open5gs-monitor
    spec:  
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - open5gs-nrf
                topologyKey: kubernetes.io/hostname
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
      containers:
        - name: pcf
          image: maikovisky/open5gs:ubuntu-latest   
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-pcf-config
              mountPath: /open5gs/config-map/pcf.yaml
              subPath: "pcf.yaml"

          command: ["open5gs-pcfd", "-c", "/open5gs/config-map/pcf.yaml"]

        # - name: metrics-pcf
        #   image: maikovisky/open5gs:ubuntu-latest    
        #   command: ["/bin/prometheus-node-exporter"]
      volumes:
        - name: open5gs-pcf-config
          configMap:
            name: open5gs-pcf-config

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-pcf
  namespace: open5gs
  labels:
    epc-mode: pcf
    release: prometheus
spec:
  selector:
    matchLabels:
      epc-mode: pcf
  endpoints:
  - interval: 5s
    port: http-open5gs-pcf-9090