apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwu-reconfig
  namespace: open5gs
  labels:
    epc-mode: sgwu
data:
  reconfig.sh: |
    #!/bin/bash
    sed "s/HOSTNAME/$HOSTNAME/g" /open5gs/config-map/sgwu.yaml > /etc/open5gs/sgwu-01.yaml
    open5gs-sgwud -d -c /etc/open5gs/sgwu-01.yaml
