{
 "title": "Open 5G",
 "tags": [
  "5g",
  "open5gs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "resolution", "query": "30s,5m,1h" },
   { "name": "interval", "label": "Intervalo", "query": "1m,10m,1h,6h,8h,12h,24h,1d, 7f" },
   {
    "name": "workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\"}, workload)"
    }
   },
   {
    "name": "ues",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\"}, workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency UE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(url, job) (ping_average_response_ms{namespace=\"$namespace\", service=~\"$ues\", url!=\"8.8.8.8\"})",
     "legendFormat": "{{job}} ({{url}})"
    },
    {
     "expr": "avg by(job, url) (ping_average_response_ms{namespace=\"$namespace\", service=~\"$ues\", url=\"8.8.8.8\"})",
     "legendFormat": "{{job}} ({{url}})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Computers Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (node_thermal_zone_temp{instance=~\"(brix-porvir-.+)\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\r\n* on (namespace,pod)\r\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\r\n* on (namespace,pod)\r\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(\r\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}\r\n  * on(namespace,pod)\r\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"$workload\" }\r\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service) (process_resident_memory_bytes{namespace=\"$namespace\", service=~\"$workload\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "PODS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "AMF Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amf_session{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GNB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnb{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active User Equipments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (ues_active{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed initial registrations at the AMF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fivegs_amffunction_rm_reginitfail{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active UPF Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(fivegs_upffunction_upf_sessionnbr{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAN UEs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ran_ue{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active GTP peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (gtp_peers_active{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Rejection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fivegs_amffunction_amf_authreject{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "N3 GTP (in)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "count by(service) (fivegs_ep_n3_gtp_indatapktn3upf{namespace=\"$namespace\"})",
     "legendFormat": "{{service}} (in) "
    }
   ]
  },
  {
   "title": "N3 GTP (out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "count by(service) (fivegs_ep_n3_gtp_outdatapktn3upf{namespace=\"$namespace\"})",
     "legendFormat": "{{service}} (out)"
    }
   ]
  },
  {
   "title": "UPF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service) (increase(fivegs_upffunction_upf_sessionnbr{namespace=\"open5gs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", container=\"iperf-ue\"} |~ `([0-9\\.]*.Bytes/sec)` | line_format `[{{ .pod }}] [{{ .container }}] {{ __line__ }}`",
     "resolution": 2
    },
    {
     "expr": "{namespace=\"$namespace\", container=\"iperf-ue\"} |~ \"Waiting [0-9].*s for new testing\" | line_format `[{{ .pod }}] [{{ .container }}] {{ __line__ }}`"
    }
   ]
  },
  { "title": "5G Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "UPF Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "sum by(job) (fivegs_upffunction_upf_sessionnbr{namespace=\"$namespace\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "UPF QoS Flow",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "sum by(job, dnn) (fivegs_upffunction_upf_qosflows{namespace=\"$namespace\"})",
     "legendFormat": "{{job}} ({{dnn}})"
    }
   ]
  },
  {
   "title": "Virtual Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service) (process_virtual_memory_bytes{namespace=\"$namespace\", service!~\"open5gs-mqtt\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by(service) (rate(process_cpu_seconds_total{namespace=\"$namespace\", service!~\"open5gs-mqtt\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network (Recive)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"upf1|upf2|upf3|upf4\"}[$__interval])",
     "legendFormat": "{{container}} "
    }
   ]
  },
  {
   "title": "Network (Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(device, service) (rate(node_network_transmit_bytes_total{namespace=\"$namespace\", device!~\"lo|tunl0\", service!=\"open5gs-my5grantester\"}[$__rate_interval])) * 8",
     "legendFormat": "{{service}} ({{device}}) (TX)"
    }
   ]
  },
  {
   "title": "Active GTP PDP Contexts (GGSN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "gtp1_pdpctxs_active{namespace=\"$namespace\"}",
     "legendFormat": "{{job}}  (GPTv1)"
    },
    {
     "expr": "gtp2_sessions_active{namespace=\"$namespace\"}",
     "legendFormat": "{{job}} (GPTv2)"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(amf_session{namespace=\"$namespace\"})",
     "legendFormat": "AMF Sessions"
    },
    {
     "expr": "sum(gnb{namespace=\"$namespace\"})",
     "legendFormat": "gNodeBs"
    },
    {
     "expr": "sum(ran_ue{namespace=\"open5gs\"})",
     "legendFormat": "RAN UEs"
    }
   ]
  },
  { "title": "Services Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Network IPERF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(device, service) (rate(node_network_transmit_bytes_total{namespace=\"open5gs\", device!~\"lo|tunl0\", service=\"open5gs-iperf\"}[$__rate_interval])) * 8",
     "legendFormat": "{{service}} ({{device}}) (TX)"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } }
 ]
}