apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: open5gs
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
        file: 
          path: /var/log/open5gs/ausf.log

    global:
      max:
        ue: 2048  # The number of UE can be increased depending on memory size.
        peer: 128

    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            advertise: open5gs-ausf
        client:
          nrf:
            - uri: http://open5gs-nrf


