apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf
  namespace: open5gs
  labels:
    epc-mode: ausf
spec:
  selector:
    epc-mode: ausf
  ports:
    - name: open5gs-ausf-tcp-80
      protocol: TCP
      port: 80
    - name: open5gs-ausf-tcp-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ausf
  namespace: open5gs
  labels:
    epc-mode: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: ausf
  template:
    metadata:    
      labels:
        epc-mode: ausf
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: metrics-ausf
          image: maikovisky/open5gs:ubuntu-latest    
          command: ["/bin/prometheus-node-exporter"]

        - name: ausf
          image: maikovisky/open5gs:ubuntu-latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-ausf-config
              mountPath: /open5gs/config-map/ausf.yaml
              subPath: "ausf.yaml"

          command: ["open5gs-ausfd", "-d", "-c", "/open5gs/config-map/ausf.yaml"]
      volumes:
        - name: open5gs-ausf-config
          configMap:
            name: open5gs-ausf-config

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-ausf
  namespace: open5gs
  labels:
    epc-mode: ausf
spec:
  selector:
    matchLabels:
      epc-mode: ausf
  endpoints:
  - interval: 30s
    port: open5gs-ausf-tcp-9100
