apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf
  namespace: open5gs
  labels:
    epc-mode: ausf
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: ausf
  ports:
    - name: http2-open5gs-ausf-80
      protocol: TCP
      port: 80
      targetPort: 80
    # - name: http-open5gs-ausf-9100
    #   protocol: TCP
    #   port: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ausf
  namespace: open5gs
  labels:
    epc-mode: ausf
    version: 2.6.4
    app: open5gs-ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: ausf
  template:
    metadata:    
      labels:
        epc-mode: ausf
        version: 2.6.4
        app: open5gs-ausf
    spec:        
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - open5gs-nrf
                topologyKey: kubernetes.io/hostname
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
        #kubernetes.io/hostname: molejo
      containers:
        - name: ausf
          image: maikovisky/open5gs:ubuntu-latest  
          #imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "200m"
          volumeMounts:
            - name: open5gs-ausf-config
              mountPath: /open5gs/config-map/ausf.yaml
              subPath: "ausf.yaml"

          command: ["open5gs-ausfd", "-c", "/open5gs/config-map/ausf.yaml"]
      volumes:
        - name: open5gs-ausf-config
          configMap:
            name: open5gs-ausf-config

