apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: open5gs
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
        file: /var/log/open5gs/ausf.log

    sbi:
      server:
        no_tls: true
        cacert: /etc/open5gs/tls/ca.crt
        key: /etc/open5gs/tls/ausf.key
        cert: /etc/open5gs/tls/ausf.crt
      client:
        no_tls: true
        cacert: /etc/open5gs/tls/ca.crt
        key: /etc/open5gs/tls/ausf.key
        cert: /etc/open5gs/tls/ausf.crt

    ausf:
        sbi:
          - dev: eth0
            advertise: open5gs-ausf
    nrf:
        sbi:
          - name: open5gs-nrf

    # scp:
    #   sbi:
    #     - name: open5gs-scp
