apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-bsf-config
  namespace: open5gs
  labels:
    epc-mode: bsf
data:
  bsf.yaml: |
    db_uri: mongodb://open5gs-mongodb-svc/open5gs
    logger:
      file: 
        path: /var/log/open5gs/bsf.log

    global:
      max:
        ue: 2048  # The number of UE can be increased depending on memory size.
        peer: 128

    bsf:
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-bsf
        client:
          nrf:
            - uri: http://open5gs-nrf