apiVersion: v1
kind: Service
metadata:
  name: open5gs-bsf
  namespace: open5gs
  labels:
    epc-mode: bsf
spec:
  selector:
    epc-mode: bsf
  ports:
    - name: open5gs-bsf-tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: open5gs-bsf-tcp-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-bsf
  namespace: open5gs
  labels:
    epc-mode: bsf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: bsf
  template:
    metadata: 
      labels:
        epc-mode: bsf
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: metrics-bsf
          image: maikovisky/open5gs:ubuntu-latest    
          command: ["/bin/prometheus-node-exporter"]
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

        - name: bsf
          image: maikovisky/open5gs:ubuntu-latest    
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-bsf-config
              mountPath: /open5gs/config-map/bsf.yaml
              subPath: "bsf.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

          command: ["open5gs-bsfd", "-d", "-c", "/open5gs/config-map/bsf.yaml"]
      volumes:
        - name: open5gs-bsf-config
          configMap:
            name: open5gs-bsf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        