apiVersion: v1
kind: Service
metadata:
  name: open5gs-bsf
  namespace: open5gs
  labels:
    epc-mode: bsf
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: bsf
  ports:
    - name: http-open5gs-bsf-80
      protocol: TCP
      port: 80
      targetPort: 80
    # - name: http-open5gs-bsf-9100
    #   protocol: TCP
    #   port: 9100
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: open5gs-bsf
#   namespace: open5gs
#   labels:
#     epc-mode: bsf
# spec:
#   selector:
#     matchLabels:
#       epc-mode: bsf
#   endpoints:
#   - interval: 30s
#     port: http-open5gs-bsf-9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-bsf
  namespace: open5gs
  labels:
    epc-mode: bsf
    version: 2.6.4
    app: open5gs-bsf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: bsf
  template:
    metadata: 
      labels:
        epc-mode: bsf
        version: 2.6.4
        app: open5gs-bsf
    spec:  
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - open5gs-nrf
                topologyKey: kubernetes.io/hostname
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
      containers:
        - name: bsf
          image: maikovisky/open5gs:ubuntu-latest  
          #imagePullPolicy: IfNotPresent  
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-bsf-config
              mountPath: /open5gs/config-map/bsf.yaml
              subPath: "bsf.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

          command: ["open5gs-bsfd", "-c", "/open5gs/config-map/bsf.yaml"]
      volumes:
        - name: open5gs-bsf-config
          configMap:
            name: open5gs-bsf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
