apiVersion: v1
kind: Service
metadata:
  name: open5gs-upf-1
  namespace: open5gs
  labels:
    epc-mode: upf1
    promotheus: open5gs-monitor
spec:
  selector:
    epc-mode: upf1
  ports:
    - name: http2-open5gs-upf1-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-open5gs-upf1-9090
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: open5gs-upf1-udp-2152
      protocol: UDP
      port: 2152
      targetPort: 2152
    - name: open5gs-upf1-udp-8805
      protocol: UDP
      port: 8805
      targetPort: 8805
    # - name: http-open5gs-upf1-9100
    #   protocol: TCP
    #   port: 9100
    #   targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-upf-1
  namespace: open5gs
  labels:
    epc-mode: upf1
    promotheus: open5gs-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: upf1
  template:
    metadata:  
      labels:
        epc-mode: upf1
        app: open5gs-upf
    spec:  
      nodeSelector:
        #kubernetes.io/arch: amd64
        #kubernetes.io/hostname: ledzeppelin
        #kubernetes.io/hostname: mac-porvir-05
        kubernetes.io/hostname: brix-porvir-01
      containers:
        - name: upf1
          image: maikovisky/open5gs:latest    
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          # resources:
          #   requests:
          #     memory: "0Mi"
          #     cpu: "900m"
          #   limits:
          #     memory: "0Mi"
          #     cpu: "900m"
          volumeMounts:
            - name: open5gs-upf1-config
              mountPath: /open5gs/config-map/upf.yaml
              subPath: "upf.yaml"

            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

           
            - name: open5gs-upf1-config
              mountPath:  /bin/entrypoint.sh
              subPath: entrypoint.sh

          #command: ["open5gs-upfd", "-c", "/open5gs/config-map/upf.yaml"]
          command: ["/bin/entrypoint.sh"]

      volumes:
        - name: open5gs-upf1-config
          configMap:
            name: open5gs-upf1-config
            defaultMode: 0777
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-upf-1
  namespace: open5gs
  labels:
    epc-mode: upf1
    prometheus: open5gs-monitor
    release: prometheus
spec:
  selector:
    matchLabels:
      epc-mode: upf1
  endpoints:
  - interval: 5s
    port: http-open5gs-upf1-9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf1-config
  namespace: open5gs
  labels:
    epc-mode: upf1
data:
  upf.yaml: |-
    logger:
      file: 
        path: /var/log/open5gs/upf.log
    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
        peer: 64

    upf:
      pfcp:
        server:
          - address: 0.0.0.0
            advertise: open5gs-upf-1
        client:
          # smf:     #  UPF PFCP Client try to associate SMF PFCP Server
          #   - address: open5gs-smf
      gtpu:
        server:
          - address: 0.0.0.0
            advertise: open5gs-upf-1
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      session:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
          dnn: internet
          dev: ogstun
        - subnet: 10.41.0.0/16
          gateway: 10.41.0.1
          dnn: slice01
          dev: slice01       

  entrypoint.sh: |-
    #!/bin/bash
    set -e

    echo "Executing k8s customized entrypoint.sh"
    #echo "Creating net device {{ .dev }}"
    if grep "ogstun" /proc/net/dev > /dev/null; then
      echo "[WARNING] Net device ogstun already exists!"
      ip addr add 192.168.0.1/16 dev ogstun || true
      ip link set ogstun up
    else 
      echo "[INFO] Create device ogstun!"
      ip tuntap add name ogstun mode tun
      ip addr add 192.168.0.1/16 dev ogstun || true
      ip link set ogstun up
    fi

    # echo "Config tun"
    # ip tuntap add name ogstun mode tun
    # ip addr add 192.168.0.1/16 dev ogstun 
    # ip link set ogstun up

    if grep "slice01" /proc/net/dev > /dev/null; then
      echo "[WARNING] Net device slice01 already exists!"
      ip addr add 10.41.0.1/16 dev slice01 || true
      ip link set slice01 up
    else 
      echo "[INFO] Create device slice01 !"
      ip tuntap add name slice01 mode tun
      ip addr add 10.41.0.1/16 dev slice01 || true
      ip link set slice01 up
    fi

    echo "[INFO] Config sysctl"
    sysctl -w net.ipv4.ip_forward=1
    sysctl -w net.ipv6.conf.all.forwarding=1

    echo "Enable NAT"
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

    if [ ! -v NICE_VALUE ]; then
        echo "RUN WITHOUT NICE"
        open5gs-upfd -c /open5gs/config-map/upf.yaml
    else
        echo "RUN WITH NICE $NICE_VALUE"
        nice -n $NICE_VALUE open5gs-upfd -c /open5gs/config-map/upf.yaml
    fi