apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-rclocal
  namespace: open5gs
  labels:
    epc-mode: upf
data:
  rc.local: |
    #!/bin/sh
    ip tuntap add name ogstun mode tun
    ip addr add 10.45.0.1/16 dev ogstun
    ip link set ogstun up
    sysctl -w net.ipv4.ip_forward=1