apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-entrypoint
  namespace: open5gs
  labels:
    epc-mode: upf
data:
  entrypoint.sh: |-
    set -e

    echo "Executing k8s customized entrypoint.sh"
    echo "Creating net device {{ .dev }}"
    if grep "ogstun" /proc/net/dev > /dev/null; then
      echo "Warnin: Net device ogstun already exists! may you need to set createDev: false";
      exit 1
    fi

    ip tuntap add name ogstun mode tun
    ip link set ogstun up
    echo "Setting IP 192.168.0.1 to device ogstun"
    ip addr add 192.168.0.1 dev ogstun;
    sysctl -w net.ipv4.ip_forward=1;

    echo "Enable NAT for 192.168.0.1 and device ogstun"
    iptables -t nat -A POSTROUTING -s 192.168.0.1 ! -o ogstun -j MASQUERADE;
