apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  namespace: open5gs
  labels:
    epc-mode: nrf
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: nrf
  #type: LoadBalancer
  ports:
    - name: http2-open5gs-nrf-80
      protocol: TCP
      port: 80
      targetPort: 80
    # - name: http-open5gs-nrf-9100
    #   protocol: TCP
    #   port: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-nrf
  namespace: open5gs
  labels:
    epc-mode: nrf
    version: 2.6.4
    app: open5gs-nrf

spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata: 
      labels:
        epc-mode: nrf
        version: 2.6.4
        app: open5gs-nrf
    spec:  
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
        #kubernetes.io/hostname: molejo

      containers:
        # - name: tcpdump-nrf
        #   image: maikovisky/open5gs:ubuntu-latest  
        #   imagePullPolicy: Always  
        #   command: ["/bin/tcpdump", "-i", "eth0", "-s", "65535", "-G", "3600", "-w", "/var/tcpdump/nrf-%F_%H%M.pcap"]
        #   volumeMounts:
        #     - name: "dev-net-tun"
        #       mountPath: "/dev/net/tun" # Needed for VPN
        #     - name: tcpdump-persistent-storage
        #       mountPath: /var/tcpdump

        - name: nrf
          image: maikovisky/open5gs:ubuntu-latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-nrf-config
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

          command: ["open5gs-nrfd", "-c", "/open5gs/config-map/nrf.yaml"]


        # - name: metrics-nrf
        #   image: maikovisky/open5gs:ubuntu-latest    
        #   command: ["/bin/prometheus-node-exporter"]
        #   volumeMounts:
        #     - name: "dev-net-tun"
        #       mountPath: "/dev/net/tun" # Needed for VPN

          

      volumes:
        - name: open5gs-nrf-config
          configMap:
            name: open5gs-nrf-config

        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

        - name: tcpdump-persistent-storage
          persistentVolumeClaim:
            claimName: open5gs-tcpdump-pv-claim

        # - name: logfile-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: open5gs-tcpdump-pv-claim
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: open5gs-nrf
#   namespace: open5gs
#   labels:
#     epc-mode: nrf
# spec:
#   selector:
#     matchLabels:
#       epc-mode: nrf
#   endpoints:
#   - interval: 30s
#     port: http-open5gs-nrf-9100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: open5gs-nrf
spec:
  host: open5gs-nrf
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: 2.6.4