apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  namespace: open5gs
  labels:
    epc-mode: nrf
spec:
  selector:
    epc-mode: nrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-nrf
  namespace: open5gs
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: nrf
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: nrf
          image: maikovisky/open5gs:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: open5gs-nrf-config
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"
            # - name: logfile-persistent-storage
            #   mountPath: /var/log/open5gs
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          command: ["open5gs-nrfd", "-c", "/open5gs/config-map/nrf.yaml"]
      volumes:
        - name: open5gs-nrf-config
          configMap:
            name: open5gs-nrf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        # - name: logfile-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: open5gs-logfile-pv-claim

