apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  namespace: open5gs
  labels:
    epc-mode: nrf
spec:
  selector:
    epc-mode: nrf
  ports:
    - name: open5gs-nrf-tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: open5gs-nrf-tcp-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-nrf
  namespace: open5gs
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: nrf
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        nodetype: server
      containers:
        - name: metrics-nrf
          image: maikovisky/open5gs:latest  
          command: ["/usr/bin/node_exporter"]

        - name: nrf
          image: maikovisky/open5gs:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: open5gs-nrf-config
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"
            # - name: logfile-persistent-storage
            #   mountPath: /var/log/open5gs
          command: ["open5gs-nrfd", "-c", "/open5gs/config-map/nrf.yaml"]
      volumes:
        - name: open5gs-nrf-config
          configMap:
            name: open5gs-nrf-config
        # - name: logfile-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: open5gs-logfile-pv-claim
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-nrf
  namespace: open5gs
  labels:
    epc-mode: nrf
spec:
  selector:
    matchLabels:
      epc-mode: nrf
  endpoints:
  - interval: 30s
    port: open5gs-nrf-tcp-9100