apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-scp-config
  namespace: open5gs
  labels:
    epc-mode: scp
data:
  scp.yaml: |
    logger:
      file: 
        path: /var/log/open5gs/scp.log
    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
        peer: 64

    scp:
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-scp
        client:
          nrf:
            - uri: http://open5gs-nrf


