apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-scp-config
  namespace: open5gs
  labels:
    epc-mode: scp
data:
  scp.yaml: |
    logger:
        file: /var/log/open5gs/scp.log

    scp:
        sbi:
          addr: 0.0.0.0
    nrf:
        sbi:
          name: open5gs-nrf
