apiVersion: v1
kind: Service
metadata:
  name: open5gs-scp-sctp
  namespace: open5gs
  labels:
    app.kubernetes.io/name: open5gs
    app.kubernetes.io/instance: ngc5gs
    app.kubernetes.io/component: open5gs-amf
spec:
  type: NodePort
  ports:
  - name: ngap
    port: 38412
    targetPort: 38412
    nodePort: 31412
    protocol: SCTP

  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: open5gs
    app.kubernetes.io/instance: ngc5gs
    app.kubernetes.io/component: open5gs-amf