apiVersion: v1
kind: Service
metadata:
  name: open5gs-scp
  namespace: open5gs
  labels:
    epc-mode: scp
spec:
  selector:
    epc-mode: scp
  ports:
    - name: open5gs-scp-tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: open5gs-scp-sctp-31412
      protocol: SCTP
      port: 31412
    - name: open5gs-scp-sctp-38412
      protocol: SCTP
      port: 38412
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-scp
  namespace: open5gs
  labels:
    epc-mode: scp
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: scp
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: scp
    spec:  
      containers:
        - name: scp
          image: maikovisky/open5gs:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: open5gs-scp-config
              mountPath: /open5gs/config-map/scp.yaml
              subPath: "scp.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
            - name: "lib-modules"
              mountPath: "/lib/modules" # Needed for VPN
          command: ["open5gs-scpd", "-c", "/open5gs/config-map/scp.yaml"]
      volumes:
        - name: open5gs-scp-config
          configMap:
            name: open5gs-scp-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: lib-modules
          hostPath:
            path: /lib/modules