apiVersion: v1
kind: Service
metadata:
  name: open5gs-scp
  namespace: open5gs
spec:
  selector:
    epc-mode: scp
  ports:
    - name: http2-open5gs-scp-80
      protocol: TCP
      port: 80
      targetPort: 80
    # - name: http-open5gs-scp-9100
    #   protocol: TCP
    #   port: 9100
    #   targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-scp
  namespace: open5gs
  labels:
    epc-mode: scp
    prometheus: open5gs-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: scp
  template:
    metadata:   
      labels:
        epc-mode: scp
        app: open5gs-scp

    spec:  
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - open5gs-nrf
                topologyKey: kubernetes.io/hostname
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
        #kubernetes.io/hostname: molejo

      containers:  
        - name: scp
          image: maikovisky/open5gs:latest    
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "200m"
          volumeMounts:
            - name: open5gs-scp-config
              mountPath: /open5gs/config-map/scp.yaml
              subPath: "scp.yaml"

            - name: "lib-modules"
              mountPath: "/lib/modules" 
          command: ["open5gs-scpd", "-c", "/open5gs/config-map/scp.yaml"]
      volumes:
        - name: open5gs-scp-config
          configMap:
            name: open5gs-scp-config

        - name: lib-modules
          hostPath:
            path: /lib/modules

