apiVersion: v1
kind: Service
metadata:
  name: open5gs-iperf
  namespace: open5gs
  labels:
    epc-mode: iperf
    promotheus: open5gs-monitor
spec:
  selector:
    epc-mode: iperf
  #clusterIP: None
  ports:
    - name: o5g-iperf-5201
      protocol: TCP
      port: 5201
      targetPort: 5201
    - name: o5g-iperf-5001
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: o5g-iperf-9100
      protocol: TCP
      port: 9100
      targetPort: 9100

---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-iperf
  namespace: open5gs
  labels:
    epc-mode: pcf
    promotheus: open5gs-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: iperf
  template:
    metadata:   
      labels:
        epc-mode: iperf
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
      #  kubernetes.io/hostname: molejo
      containers:       
        - name: iperf3
          image: maikovisky/iperf:latest  
          ports:
            - containerPort: 5201
              name: o5g-iperf-5201
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]  
          command: ["/bin/iperf3", "-s"]
     
        - name: iperf
          image: maikovisky/iperf:latest  
          ports:
            - containerPort: 5001
              name: o5g-iperf-5001
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]  
          command: ["/bin/iperf", "-s"]
        
        - name: metrics-iperf
          image: maikovisky/iperf:latest  
          command: ["/bin/prometheus-node-exporter"]
          ports:
            - containerPort: 9100
              name: o5g-iperf-9100

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-iperf
  namespace: open5gs
  labels:
    epc-mode: iperf
spec:
  selector:
    matchLabels:
      epc-mode: iperf
  endpoints:
  - interval: 30s
    port: open5gs-iperf-tcp-9100
