apiVersion: v1
kind: Service
metadata:
  name: open5gs-iperf04
  namespace: open5gs
  labels:
    epc-mode: iperf04
    promotheus: open5gs-monitor
spec:
  selector:
    epc-mode: iperf04
  ports:
    - name: o5g-iperf04-5201
      protocol: TCP
      port: 5201
      targetPort: 5201
    - name: o5g-iperf04-udp-5202
      protocol: UDP
      port: 5202
      targetPort: 5202

    - name: o5g-iperf04-5001
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: o5g-iperf04-udp-5002
      protocol: UDP
      port: 5002
      targetPort: 5002
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-iperf04
  namespace: open5gs
  labels:
    epc-mode: iperf04
    promotheus: open5gs-monitor
    app: iperf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: iperf04
  template:
    metadata:   
      labels:
        epc-mode: iperf04
        app: iperf
    spec:  
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: prometheus
                operator: In
                values:
                - k8s
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {monitoring}

             
      nodeSelector:
          kubernetes.io/arch: amd64
          nodetype: server     
        #kubernetes.io/arch: amd64
        #kubernetes.io/hostname: acdc
        #kubernetes.io/hostname: mac-porvir-05
        #kubernetes.io/hostname: erasure
      containers:       
        - name: iperf3
          image: maikovisky/iperf:latest  
          ports:
            - containerPort: 5201
              protocol: TCP
            - containerPort: 5201
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]  
          command: ["/bin/iperf3", "-s", "-B", "0.0.0.0", "-V", "--forceflush"]
     
        - name: iperf
          image: maikovisky/iperf:latest  
          ports:
            - containerPort: 5001
              protocol: TCP              
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]  
          command: ["/bin/iperf", "-s", "--histograms"]

        - name: iperf-udp
          image: maikovisky/iperf:latest  
          ports:       
            - containerPort: 5002
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]  
          command: ["/bin/iperf", "-s", "--sum-dstip", "--udp-histograms", "-u", "-p", "5002"]
        
        