apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    smf:
      sbi:
        - dev: eth0
          port: 80
          advertise: open5gs-smf
      metrics:
        addr: 0.0.0.0
        port: 9090
      pfcp:
        - dev: eth0
      gtpc:
        - dev: eth0
      gtpu:
        - dev: eth0
      subnet:
        - addr: 192.168.0.1/16
          dnn: internet
        - addr: 10.41.0.1/16
          dnn: slice01
        - addr: 10.42.0.1/16
          dnn: slice02
        - addr: 10.43.0.1/16
          dnn: slice03
        - addr: 10.44.0.1/16
          dnn: slice04
        - addr: 10.45.0.1/16
          dnn: slice05
        - addr: 10.46.0.1/16
          dnn: slice06
        - addr: 10.47.0.1/16
          dnn: slice07
        - addr: 10.48.0.1/16
          dnn: slice08
        - addr: 10.49.0.1/16
          dnn: slice09
        - addr: 10.50.0.1/16
          dnn: slice10
        - addr: 10.51.0.1/16
          dnn: slice11
        - addr: 10.52.0.1/16
          dnn: slice12
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1370
      ctf:
        enabled: auto
      freeDiameter: /etc/freeDiameter/smf.conf
      info:
        - s_nssai:
          - sst: 1
            dnn:
              - internet
          - sst: 1
            sd: 000001
            dnn:
              - slice01
          - sst: 2
            sd: 2
            dnn:
              - slice02
          - sst: 3
            sd: 000003
            dnn:
              - slice03
          - sst: 4
            sd: 000004
            dnn:
              - slice04
          - sst: 5
            sd: 000005
            dnn:
              - slice05
        - s_nssai:

          - sst: 6
            sd: 000006
            dnn:
              - slice06
          - sst: 7
            sd: 000007
            dnn:
              - slice07
          - sst: 8
            sd: 000008
            dnn:
              - slice08
        # - s_nssai:
        #   - sst: 9
        #     sd: 000009
        #     dnn:
        #       - slice09
        #   - sst: 10
        #     sd: 000010
        #     dnn:
        #       - slice10
        #   - sst: 11
        #     sd: 000011
        #     dnn:
        #       - slice11
        #   - sst: 12
        #     sd: 000012
        #     dnn:
        #       - slice12
        
    nrf:
      sbi:
        - name: open5gs-nrf
    
    # scp:
    #   sbi:
    #     - name: open5gs-scp

    upf:
      pfcp:
        # - addr: open5gs-upf
        #   dnn: [internet]
        - addr: open5gs-upf-1
          dnn: [internet, slice01]
        - addr: open5gs-upf-2
          dnn: [internet, slice02]
        - addr: open5gs-upf-3
          dnn: [internet, slice03]
        - addr: open5gs-upf-4
          dnn: [internet, slice04]
        - addr: open5gs-upf-5
          dnn: [internet, slice05]
        - addr: open5gs-upf-6
          dnn: [internet, slice06]
        - addr: open5gs-upf-7
          dnn: [internet, slice07]
        - addr: open5gs-upf-8
          dnn: [internet, slice08]
        - addr: open5gs-upf-9
          dnn: [internet, slice09]
        - addr: open5gs-upf-10
          dnn: [internet, slice10]
        - addr: open5gs-upf-11
          dnn: [internet, slice11]
        - addr: open5gs-upf-12
          dnn: [internet, slice12]

    metrics:
        addr: 0.0.0.0
        port: 9090

    time:
      nf_instance:
        heartbeat: 20
      message:
        duration: 3000
      handover:
        duration: 500
