apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    smf:
      sbi:
        - dev: eth0
          port: 80
          advertise: open5gs-smf
      metrics:
        addr: 0.0.0.0
        port: 9090
      pfcp:
        - dev: eth0
      gtpc:
        - dev: eth0
      gtpu:
        - dev: eth0
      subnet:
        - addr: 192.168.0.1/16
          dnn: internet
        - addr: 10.41.0.1/16
          dnn: slice01
        - addr: 10.42.0.1/16
          dnn: slice02
        - addr: 10.43.0.1/16
          dnn: slice03
        - addr: 10.44.0.1/16
          dnn: slice04
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1400
      ctf:
        enabled: auto
      freeDiameter: /etc/freeDiameter/smf.conf
      info:
        - s_nssai:
          - sst: 1
            dnn:
              - internet
          - sst: 1
            sd: 000001
            dnn:
              - slice01
          - sst: 2
            sd: 000002
            dnn:
              - slice02
          - sst: 3
            sd: 000003
            dnn:
              - slice03
          - sst: 4
            sd: 000004
            dnn:
              - slice04


        
    # nrf:
    #   sbi:
    #     - name: open5gs-nrf
    
    scp:
      sbi:
        - name: open5gs-scp

    upf:
      pfcp:
        # - addr: open5gs-upf
        #   dnn: [internet]
        - addr: open5gs-upf-1
          dnn: [internet, slice01]
        - addr: open5gs-upf-2
          dnn: [internet, slice02]
        - addr: open5gs-upf-3
          dnn: [internet, slice03]
        - addr: open5gs-upf-4
          dnn: [internet, slice04]

    metrics:
        addr: 0.0.0.0
        port: 9090


