apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    smf:
      freeDiameter: /etc/freeDiameter/smf.conf
      sbi:
        - addr: 0.0.0.0
          port: 80
          advertise: open5gs-smf
      metrics:
        addr: 0.0.0.0
        port: 9090
      pfcp:
        - dev: eth0
      gtpc:
        - dev: eth0
      gtpu:
        - dev: eth0
      subnet:
        - addr: 192.168.0.1/16
          dnn: internet
        - addr: 2001:db8:cafe::1/48
        - addr: 10.46.0.1/16
          dnn: slice01
        - addr: 10.47.0.1/16
          dnn: slice02
        - addr: 10.48.0.1/16
          dnn: slice03
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1400
      ctf:
        enabled: auto
        
    nrf:
      sbi:
        name: open5gs-nrf

    upf:
      pfcp:
        - addr: open5gs-upf
          dnn: [internet, slice01, slice02]
        - addr: open5gs-upf2
          dnn: [slice03]

    metrics:
        addr: 0.0.0.0
        port: 9090

    scp:
      sbi:
        - addr: open5gs-scp
