apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    smf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
      pfcp:
        - addr: 0.0.0.0
        - addr: ::1
      gtpc:
        - addr: 0.0.0.0
        - addr: ::1
      gtpu:
        - addr: 0.0.0.0
        - addr: ::1
      subnet:
        - addr: 10.45.0.1/16
        - addr: 2001:db8:cafe::1/48
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1400
      ctf:
        enabled: auto
        freeDiameter: /etc/freeDiameter/smf.conf
        
    nrf:
      sbi:
        name: open5gs-nrf

    upf:
    #    pfcp:
    #      - addr: open5gs-upf

    metrics:
        addr: open5gs-mme
        port: 9090