apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
      file: 
        path: /var/log/open5gs/smf.log

    global:
      max:
        ue: 2048  # The number of UE can be increased depending on memory size.
        peer: 128

    smf:
      sbi:
        server:
          - address: 0.0.0.0
            advertise: open5gs-smf
        client:
          nrf:
            - uri: http://open5gs-nrf
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      pfcp:
        server:
          - address: 0.0.0.0
            advertise: open5gs-smf
        client:
          upf:
            # - address: open5gs-upf
            #   dnn: [internet]
            - address: open5gs-upf-1
              dnn: [internet, slice01]
            - address: open5gs-upf-2
              dnn: [internet, slice02]
            - address: open5gs-upf-3
              dnn: [internet, slice03]
            - address: open5gs-upf-4
              dnn: [internet, slice04]
            - address: open5gs-upf-5
              dnn: [internet, slice05]
            # - address: open5gs-upf-6
            #   dnn: [internet, slice06]
            # - address: open5gs-upf-7
            #   dnn: [internet, slice07]
            # - address: open5gs-upf-8
            #   dnn: [internet, slice08]
            # - address: open5gs-upf-9
            #   dnn: [internet, slice09]
            # - address: open5gs-upf-10
            #   dnn: [internet, slice10]
            # - address: open5gs-upf-11
            #   dnn: [internet, slice11]
            # - address: open5gs-upf-12
            #   dnn: [internet, slice12]

      gtpc:
        server:
          - address: 0.0.0.0
            advertise: open5gs-smf
      gtpu:
        server:
          - address: 0.0.0.0
            advertise: open5gs-smf
      session:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
          dnn: internet
        - subnet: 10.41.0.1/16
          gateway: 10.41.0.1
          dnn: slice01
        - subnet: 10.42.0.0/16
          gateway: 10.42.0.1
          dnn: slice02
        - subnet: 10.43.0.0/16
          gateway: 10.43.0.1
          dnn: slice03
        - subnet: 10.44.0.0/16
          gateway: 10.44.0.1
          dnn: slice04
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: slice05
        # - subnet: 10.46.0.0/16
        #   gateway: 10.46.0.1
        #   dnn: slice06
        # - subnet: 10.47.0.0/16
        #   gateway: 10.47.0.1
        #   dnn: slice07
        # - subnet: 10.48.0.0/16
        #   gateway: 10.48.0.1
        #   dnn: slice08
        # - subnet: 10.49.0.0/16
        #   gateway: 10.49.0.1
        #   dnn: slice09
        # - subnet: 10.50.0.0/16
        #   gateway: 10.50.0.1
        #   dnn: slice10
        # - subnet: 10.51.0.0/16
        #   gateway: 10.51.0.1
        #   dnn: slice11
        # - subnet: 10.52.0.0/16
        #   gateway: 10.52.0.1
        #   dnn: slice12
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1370
      #ctf:
      # enabled: auto
      freeDiameter: /etc/freeDiameter/smf.conf
      info:
        - s_nssai:
          - sst: 1
            dnn:
              - internet
          - sst: 1
            sd: 000001
            dnn:
              - slice01
          - sst: 2
            sd: 000002
            dnn:
              - slice02
          - sst: 3
            sd: 000003
            dnn:
              - slice03
          - sst: 4
            sd: 000004
            dnn:
              - slice04
          - sst: 5
            sd: 000005
            dnn:
              - slice05
        # - s_nssai:

        #   - sst: 6
        #     sd: 000006
        #     dnn:
        #       - slice06
        #   - sst: 7
        #     sd: 000007
        #     dnn:
        #       - slice07
        #   - sst: 8
        #     sd: 000008
        #     dnn:
        #       - slice08
        # - s_nssai:
        #   - sst: 9
        #     sd: 000009
        #     dnn:
        #       - slice09
        #   - sst: 10
        #     sd: 000010
        #     dnn:
        #       - slice10
        #   - sst: 11
        #     sd: 000011
        #     dnn:
        #       - slice11
        #   - sst: 12
        #     sd: 000012
        #     dnn:
        #       - slice12
        

    #  o Security Indication(5G Core only)
    #  security_indication:
    #    integrity_protection_indication: required|preferred|not-needed
    #    confidentiality_protection_indication: required|preferred|not-needed
    #    maximum_integrity_protected_data_rate_uplink: bitrate64kbs|maximum-UE-rate
    #    maximum_integrity_protected_data_rate_downlink: bitrate64kbs|maximum-UE-rate
