apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: open5gs
  labels:
    epc-mode: webui
spec:
  selector:
    epc-mode: webui
  ports:
    - name: open5gs-webui-tcp-80
      protocol: TCP
      port: 80
    - name: open5gs-webui-tcp-3000
      protocol: TCP
      port: 3000
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-webui
  namespace: open5gs
  labels:
    epc-mode: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: webui
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: webui
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: webui
          image: maikovisky/open5gs-webui:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          env:
            - name: DB_URI 
              value: mongodb://open5gs-mongodb-svc/open5gs
            - name: HOSTNAME
              value: 0.0.0.0
          command: ["npm", "run", "dev"]
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

