apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-lucas-my5gtester-script
  namespace: open5gs
  labels:
    epc-mode: my5gtester
data:
  run.sh: |-
    set -e

    echo "Executing k8s customized entrypoint.sh"
    #echo "Creating net device {{ .dev }}"
    #if grep "ogstun" /proc/net/dev > /dev/null; then
    #  echo "Warnin: Net device ogstun already exists! may you need to set createDev: false";
    #  exit 1
    #fi

    echo "Config tun"
    ip tuntap add name ogstun mode tun
    echo "Config tun 2"
    ip addr add 192.168.0.1 dev ogstun;
    echo "Config tun 3"
    ip addr add 2001:db8:cafe::1/48 dev ogstun
    echo "Config tun 4"
    ip link set ogstun up

    echo "Config sysctl"
    sysctl -w net.ipv4.ip_forward=1;
    sysctl -w net.ipv6.conf.all.forwarding=1

    echo "Enable NAT for 192.168.0.1 and device ogstun"
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

