apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-my5gran01
  namespace: open5gs
  labels:
    epc-mode: my5gran01
    prometheus: open5gs-monitor
spec:
  replicas: 0
  selector:
    matchLabels:
      epc-mode: my5gran01
  template:
    metadata:
      labels:
        epc-mode: my5gran01
        version: 1.0.1
        app: open5gs-my5grantester
    spec:
      nodeSelector:
        kubernetes.io/hostname: brix-porvir-02
      initContainers:
        - name: init-my5gtester
          image:  maikovisky/mygranttester:1.0.1-3-ubuntu
          imagePullPolicy: IfNotPresent
          command: ["/bin/my5gtester-init"]
          env:            
            - name: DATABASE_URL
              value: mongodb://open5gs-mongodb-svc:27017
            - name: IMSI
              value: "999700000000000"
            - name: RANDOM_SLICE
              value: "False"
            - name: SLICE
              value: "1"
          volumeMounts:
            - name: open5gs-my5gtester-init
              mountPath: /bin/my5gtester-init
              subPath: "my5gtester-init"

            - name: open5gs-ue-init
              mountPath: "/bin/initUE.py"
              subPath: "initUE.py"

            - name: config-tmp
              mountPath:  /my5G-RANTester/config

      containers:
        - name: my5grantester
          image:   maikovisky/mygranttester:1.0.1-3-ubuntu
          #command: ["sleep", "20d"]
          command: ["./app", "load-test", "-n", "1"]
          volumeMounts:
            - name: config-tmp
              mountPath:  /my5G-RANTester/config

          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true

        - name: iperf-ue
          image: maikovisky/mygranttester:1.0.1-3-ubuntu
          imagePullPolicy: IfNotPresent  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          env:  
            - name: SLICE
              value: "1"
          command: ["/bin/running"]
          #command: ["sleep", "1d"]
          volumeMounts:
            - name: open5gs-my5gtester-running
              mountPath: /bin/running
              subPath: "running"

        - name: "telegraf"
          image: "telegraf:latest"
          imagePullPolicy: IfNotPresent  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-my5gran01-telegraf-cfg
              mountPath: /etc/telegraf


      volumes:
        - name: open5gs-mygtester-config
          configMap:
            name: open5gs-mygtester-config

        - name: open5gs-my5gtester-init
          configMap:
            name: open5gs-my5gtester-init
            defaultMode: 0777

        - name: open5gs-my5gtester-running
          configMap:
            name: open5gs-my5gtester-video-4k
            defaultMode: 0777

        - name: open5gs-my5gran01-telegraf-cfg
          configMap:
            name: open5gs-my5gran01-telegraf-cfg
            defaultMode: 0777

        - name: open5gs-ue-init
          configMap:
            name: open5gs-ue-init
            defaultMode: 0777

        - name: config-tmp
          emptyDir: {}



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-my5gran01-telegraf-cfg
  namespace: open5gs
data:
  telegraf.conf: |+
    [[outputs.prometheus_client]]
      ## Address to listen on.
      listen = ":9100"

    [[inputs.ping]]
      urls = ["10.0.13.188"]
      interface = "uetun1"
      method = "native"
      #percentiles = [25, 50, 95, 99]
      ping_interval = 2.0
      count = 5
      timeout = 2.0

---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-my5gran01
  namespace: open5gs
  labels:
    epc-mode: my5gran01
spec:
  selector:
    epc-mode: my5gran01
  ports:
    - name: http2-open5gs-my5gran01-9100
      protocol: TCP
      port: 9100


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-my5gran01
  namespace: open5gs
  labels:
    epc-mode: my5gran01
    release: prometheus
spec:
  selector:
    matchLabels:
      epc-mode: my5gran01
  endpoints:
  - interval: 10s
    port: http2-open5gs-my5gran01-9100
