# apiVersion: v1
# kind: Service
# metadata:
#   name: open5gs-iperf
#   namespace: open5gs
#   labels:
#     epc-mode: iperf
#     promotheus: open5gs-monitor
# spec:
#   selector:
#     epc-mode: iperf
#   # type: LoadBalancer
#   ports:
#     - name: open5gs-iperf-tcp-5001
#       protocol: TCP
#       port: 5001
#       targetPort: 5001
#     - name: open5gs-iperf-tcp-9100
#       protocol: TCP
#       port: 9100
#       targetPort: 9100
# ---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-lucas-my5gtester
  namespace: open5gs
  labels:
    epc-mode: my5gtester
#    promotheus: open5gs-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: my5gtester
  template:
    metadata:   
      labels:
        epc-mode: my5gtester
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: my5gtester
          image: lafschierholt/my5grantester-db-filler 
          env:
            - name: DB_URI 
              value: mongodb://open5gs-mongodb-svc/open5gs
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]  
          command: ["sleep", "1d"]

          volumeMounts:
            - name: open5gs-lucas-my5gtester-script
              mountPath: /bin/run.sh
              subPath: "run.sh"

            - name: open5gs-lucas-my5gtester-config
              mountPath: /etc/config.conf
              subPath: "config.conf"

      volumes:
        - name: open5gs-lucas-my5gtester-config
          configMap:
            name: open5gs-lucas-my5gtester-config
        
        - name: open5gs-lucas-my5gtester-script
          configMap:
            name: open5gs-lucas-my5gtester-script
            defaultMode: 0777       
#---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: open5gs-iperf
#   namespace: open5gs
#   labels:
#     epc-mode: iperf
# spec:
#   selector:
#     matchLabels:
#       epc-mode: iperf
#   endpoints:
#   - interval: 30s
#     port: open5gs-iperf-tcp-9100
