apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-my5gtester-iot
  namespace: open5gs
  labels:
    epc-mode: my5gtester
data:
  running: |
    #!/bin/bash 
    set -e

    sleep "15s"

    COUNTER=0
    while [ -z  $(ifconfig | awk  '/uetun/{print $1; exit}') ] 
    do
      let COUNTER=COUNTER+1
      #echo -ne "Waiting create tunnel interface. Attempt $COUNTER"\\r
      echo "Waiting create tunnel interface. Attempt $COUNTER"
      sleep "2s"
      if [ $COUNTER -eq 5 ]; then
        echo "Tunnel interface not created"
        exit 1
      fi
    done
    tunnel=$(ifconfig uetun1 | awk '/inet / {print $6}')
    
    route add -host open5gs-iperf0$SLICE dev uetun1
    while :
    do
      t=1800
      iperf -c open5gs-iperf0$SLICE -B $tunnel -t $t -i 15 -b 500K -l 48  
    done
    