apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-mygtester-config2
  namespace: open5gs
  labels:
    epc-mode: my5gtester
data:
  config-base.yml: |-
    gnodeb:
      controlif:
        ip: "HOSTNAME"
        port: 9487
      dataif:
        ip: "HOSTNAME"
        port: 2152
      plmnlist:
        mcc: "999"
        mnc: "70"
        tac: "000001"
        gnbid: "000003"
      slicesupportlist:
        sst: "1"
        sd: "1"

    ue:
      msin: "MSIN"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      amf: "8000"
      sqn: "0000000"
      dnn: "slice01"
      hplmn:
        mcc: "999"
        mnc: "70"
      snssai:
        sst: "1"
        sd: "1"

    amfif:
      ip: "open5gs-amf2-sctp"
      port: 38412

    logs:
      level: 4