apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcrf
  namespace: open5gs
  labels:
    epc-mode: pcrf
spec:
  selector:
    epc-mode: pcrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-pcrf
  namespace: open5gs
  labels:
    epc-mode: pcrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: pcrf
  template:
    metadata:  
      labels:
        epc-mode: pcrf
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: pcrf
          image: maikovisky/open5gs:latest 

          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
              
          volumeMounts:
            - name: open5gs-pcrf-config
              mountPath: /open5gs/config-map/pcrf.yaml
              subPath: "pcrf.yaml"
            - name: freediameter-pcrf-config
              mountPath: /etc/freeDiameter/pcrf.conf
              subPath: "pcrf.conf"

          command: ["open5gs-pcrfd", "-c", "/open5gs/config-map/pcrf.yaml"]
          #command: ["sleep", "1d"]
      volumes:
        - name: open5gs-pcrf-config
          configMap:
            name: open5gs-pcrf-config
        - name: freediameter-pcrf-config
          configMap:
            name: freediameter-pcrf-config



