apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwu-config
  namespace: open5gs
  labels:
    epc-mode: sgwu
data:
  sgwu.yaml: |
    logger:
        file: /var/log/open5gs/sgwu.log

    sgwu:
        gtpc:
          - addr: 127.0.0.6
        pfcp:
          - addr: 127.0.0.6
    sgwc:
