apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu
  namespace: open5gs
  labels:
    epc-mode: sgwu
spec:
  selector:
    epc-mode: sgwu
  ports:
    - name: open5gs-sgwu-udp-8805
      protocol: UDP
      port: 8805
    - name: open5gs-sgwu-udp-2152
      protocol: UDP
      port: 2152
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-sgwu
  namespace: open5gs
  labels:
    epc-mode: sgwu
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: sgwu
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: sgwu
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: sgwu
          image: maikovisky/open5gs:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: open5gs-sgwu-config
              mountPath: /open5gs/config-map/sgwu.yaml
              subPath: "sgwu.yaml"   
            - name: open5gs-sgwu-reconfig
              mountPath: /bin/reconfig.sh
              subPath: "reconfig.sh"            
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          #command: ["open5gs-sgwud", "-d","-c", "/open5gs/config-map/sgwu.yaml"]
          command: ["sleep", "1d"]
      volumes:
        - name: open5gs-sgwu-config
          configMap:
            name: open5gs-sgwu-config
        - name: open5gs-sgwu-reconfig
          configMap:
            name: open5gs-sgwu-reconfig
            defaultMode: 0777
        - name: open5gs-sgwu-netconf
          configMap:
            name: open5gs-sgwu-netconf
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

