apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwu-config
  namespace: open5gs
  labels:
    epc-mode: sgwu
data:
  sgwu.yaml: |
    logger:
        file: /var/log/open5gs/sgwu.log

    sgwu:
        gtpu:
          - addr: 0.0.0.0
        pfcp:
          - addr: 0.0.0.0

    sgwc:
      pfcp:
        addr: open5gs-sgwc
