apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-new
  namespace: monitoring
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi