apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  namespace: open5gs
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    db_uri: mongodb://open5gs-mongodb-svc/open5gs
    logger:
        file: /var/log/open5gs/udr.log
    
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    udr:
        sbi:
          - dev: eth0
            advertise: open5gs-udr

    scp:
        sbi:
          - name: open5gs-scp