apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  namespace: open5gs
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    db_uri: mongodb://open5gs-mongodb-svc/open5gs
    logger:
      file: 
        path: /var/log/open5gs/udr.log
    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
        peer: 64

    udr:
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-udr
        client:
          nrf:
            - uri: http://open5gs-nrf
