apiVersion: v1
kind: Service
metadata:
  name: open5gs-udr
  namespace: open5gs
  labels:
    epc-mode: udr
spec:
  selector:
    epc-mode: udr
  ports:
    - name: open5gs-udr-tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: open5gs-udr-tcp-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-udr
  namespace: open5gs
  labels:
    epc-mode: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udr
  template:
    metadata:   
      labels:
        epc-mode: udr
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: metrics-udr
          image: maikovisky/open5gs:ubuntu-latest    
          command: ["/bin/prometheus-node-exporter"]

        - name: udr
          image: maikovisky/open5gs:ubuntu-latest    
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-udr-config
              mountPath: /open5gs/config-map/udr.yaml
              subPath: "udr.yaml"

          command: ["open5gs-udrd", "-d", "-c", "/open5gs/config-map/udr.yaml"]
      volumes:
        - name: open5gs-udr-config
          configMap:
            name: open5gs-udr-config

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-udr
  namespace: open5gs
  labels:
    epc-mode: udr
spec:
  selector:
    matchLabels:
      epc-mode: udr
  endpoints:
  - interval: 30s
    port: open5gs-udr-tcp-9100
