apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwc-reconfig
  namespace: open5gs
  labels:
    epc-mode: sgwc
data:
  reconfig.sh: |
    #!/bin/bash
    #apk add iproute2
    #ip tuntap add name ogstun mode tun
    #ip link show
    #ip addr add 10.45.0.1/16 dev ogstun
    #ip addr add 2001:db8:cafe::1/48 dev ogstun
    #sudo ip link set ogstun up
    #ip link show
    sed "s/HOSTNAME/$HOSTNAME/g" /open5gs/config-map/sgwc.yaml > /etc/open5gs/sgwc-01.yaml
