apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwc-config
  namespace: open5gs
  labels:
    epc-mode: sgwc
data:
  sgwc.yaml: |
    logger:
        file: /var/log/open5gs/sgwc.log

    sgwc:
        gtpc:
          - addr: 127.0.0.3
        pfcp:
          - addr: 127.0.0.3
    sgwu:
        pfcp:
          - addr: 127.0.0.6
