apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwc
  namespace: open5gs
  labels:
    epc-mode: sgwc
spec:
  selector:
    epc-mode: sgwc
  ports:
    - protocol: TCP
      port: 8805
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-sgwc
  namespace: open5gs
  labels:
    epc-mode: sgwc
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: sgwc
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: sgwc
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: molejo
      containers:
        - name: sgwc
          image: maikovisky/open5gs:latest  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          #imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          volumeMounts:
            - name: open5gs-sgwc-config
              mountPath: /open5gs/config-map/sgwc.yaml
              subPath: "sgwc.yaml"
            - name: open5gs-sgwc-reconfig
              mountPath: /bin/reconfig.sh
              subPath: "reconfig.sh"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          #command: ["open5gs-sgwcd", "-c", "/open5gs/config-map/sgwc.yaml"]
          command: ["sleep", "1d"]
      volumes:
        - name: open5gs-sgwc-config
          configMap:
            name: open5gs-sgwc-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: open5gs-sgwc-reconfig
          configMap:
            name: open5gs-sgwc-reconfig
            defaultMode: 0777

