apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwc-config
  namespace: open5gs
  labels:
    epc-mode: sgwc
data:
  sgwc.yaml: |
    logger:
        file: /var/log/open5gs/sgwc.log

    sgwc:
        gtpc:
          - addr: HOSTNAME
        pfcp:
          - addr: HOSTNAME
    sgwu:
        pfcp:
          - addr: open5gs-sgwu
    
    # End of file
    
