apiVersion: v1
kind: Namespace
metadata:
  name: open5gs
  labels:
    kubernetes.io/metadata.name: open5gs
    serviceMonitor: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: open5gs
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/namespaces/open5gs/rolebindings/prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: open5gs
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/open5gs/roles/prometheus-k8s
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
      - endpoints
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
    resources:
      - ingresses
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs
  namespace: open5gs
  labels:
    app.kubernetes.io/name: open5gs
    app.kubernetes.io/component: amf
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: open5gs
      app.kubernetes.io/component: amf
  endpoints:
    - port: open5gs-amf-tcp-9090
    # - port: open5gs-upf-tcp-9090
    # - port: open5gs-smf-tcp-9090